experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../../data/{0}/train.tsv
    # validation_path: ../../data/{0}/validationset.tsv
    test_path: ../../data/{0}/test.tsv
    side_information:
      - dataloader: SalvatoreAttributes
        interactions: ../../data/{0}/decision_path_gini_1.tsv
  dataset: yahoo_movies
  prefiltering:
    strategy: iterative_k_core
    core: 10
  top_k: 50
  evaluation:
    cutoffs: 10
    simple_metrics: [Recall, HR, nDCG, Precision, F1, MAP, MAR, LAUC, ItemCoverage, nDCGRendle2020, Gini, SEntropy, EFD, EPC]
  gpu: 0
  external_models_path: ../../external/models/__init__.py
  models:
    external.EGCFv2:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall
        restore: False
      lr: [loguniform, -8.90775527898, -6.90775527898]
      n_layers: 3
      # n_layers: [quniform, 2, 3, 1]
      epochs: 400
      batch_size: 256
      emb: 64
      l_w: [quniform, 10e-5, 10, 100]
      edge_features_path: data/yahoo_movies/prova.tsv
