experiment:
  backend: pytorch
  dataset: yahoo-movies
  data_config:
    strategy: dataset
    dataset_path: ../../data/{0}/dataset.tsv
  prefiltering:
    - strategy: iterative_k_core
      core: 10
    - strategy: global_threshold
      threshold: 3
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
    save_on_disk: True
    save_folder: split/{0}/10core
  top_k: 50
  evaluation:
    cutoffs: 10
    simple_metrics: [Recall, HR, nDCG, Precision, F1, MAP, MAR, LAUC, ItemCoverage, nDCGRendle2020, Gini, SEntropy, EFD, EPC]
  gpu: 0
  external_models_path: ../../external/models/__init__.py
  models:
    external.EGCFv2:
      meta:
        hyper_max_evals: 10
        hyper_opt_alg: tpe
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall
        restore: False
      lr: [loguniform, -8.90775527898, -6.90775527898]
        # -6.90775527898, -4.90775527898
      n_layers: [quniform, 2, 3, 1]
      epochs: 400
      batch_size: 256
      emb: 64
      l_w: [quniform, 10e-5, 10, 100]
      edge_features_path: data/yahoo/V2_decision_path_entropy_1.tsv
      emb_f: 10
      # emb_f = 10

